service: default
runtime: nodejs22
instance_class: F1

env_variables: 
  GOOGLE_PROJECT_ID: "513090361622"
  GOOGLE_PROJECT_REF: "learn-swiss-german-eff37"
  GOOGLE_CLOUD_LOCATION: "global"
  GOOGLE_CLOUD_QUEUE_LOCATION: "europe-central2"
  GOOGLE_GENAI_USE_VERTEXAI: "true"
  WORKER_SERVICE_URL: "https://worker-dot-learn-swiss-german-eff37.lm.r.appspot.com/process-job"

# Use automatic scaling, as this service handles fluctuating web traffic.
automatic_scaling:
  min_instances: 0 # Scales down to zero to save costs when idle.
  max_instances: 10

handlers:
  - url: /(.*\.(html|json|ico))$
    static_files: dist/\1
    upload: dist/.*\.(html|json|ico)$
    expiration: "0s"
    secure: always  # <--- Forces HTTPS
    http_headers:
      Cache-Control: "no-store, no-cache, must-revalidate"